### PR TITLE
Cleanup includes and header guards

### PR DESCRIPTION
**Pull request by Pesa**

### CODE REVIEW

**Comment by Pesa** [comment]
@tylerliu

**Comment by tylerliu** [comment]
Looks good but let me figure out macOS build first......

**Comment by Pesa** [comment]
> Looks good but let me figure out macOS build first......

well, good luck with that :)
openabe won't build on newer versions of macOS/Xcode because of a conflict with the C++ standard header `<version>`, as we found out during the hackathon...

**Comment by tylerliu** [comment]
> > Looks good but let me figure out macOS build first......
> 
> well, good luck with that :) openabe won't build on newer versions of macOS/Xcode because of a conflict with the C++ standard header `<version>`, as we found out during the hackathon...

Yea, but hopefully we can get 10.15 working.

**Comment by tylerliu** [comment]
Would you mind rebase to the new CI script so we can check on MacOS? Thanks.

**Comment by tylerliu** [comment]
Also #13? Thanks.

**Pull request merged**
